---
minimum_pre_commit_version: 2.4.0
repos:
  # ----- Formatting ---------------------------------------------------------------------------->
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.7+
        args: [
          --py37-plus
        ]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args: [
          --py37-plus,
        ]

  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args: [-l 100, -S]

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^docs/.*\.md$
        additional_dependencies: [black==21.7b0]
  # <---- Formatting -----------------------------------------------------------------------------

  # ----- Security ------------------------------------------------------------------------------>
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        name: Run bandit against the code base
        args: [--silent, -lll]
  # <---- Security -------------------------------------------------------------------------------
